server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 最大连接
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
        max-wait: 100 # 连接等待时间

  rabbitmq:
    host: 127.0.0.1
    port: 5672


test:
  - daq:
      name: daioaqi
      age: 23
      sex: man
  - wt:
      name: wutong
      age: 26
      sex: woman